# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Py\Report_project\report_project_ui_002.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(904, 714)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMouseTracking(False)
        MainWindow.setAcceptDrops(False)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setWindowFilePath("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(884, 0))
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setObjectName("centralwidget")
        self.createReportButton = QtWidgets.QPushButton(self.centralwidget)
        self.createReportButton.setGeometry(QtCore.QRect(9, 662, 621, 23))
        self.createReportButton.setCheckable(False)
        self.createReportButton.setObjectName("createReportButton")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 621, 631))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.inputField = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.inputField.setObjectName("inputField")
        self.horizontalLayout.addWidget(self.inputField)
        self.outputField = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.outputField.setObjectName("outputField")
        self.horizontalLayout.addWidget(self.outputField)
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(640, 20, 241, 81))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.percentageButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.percentageButton.setObjectName("percentageButton")
        self.gridLayout_2.addWidget(self.percentageButton, 2, 0, 1, 1)
        self.hours = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.hours.setProperty("value", 40)
        self.hours.setObjectName("hours")
        self.gridLayout_2.addWidget(self.hours, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.grade = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.grade.setObjectName("grade")
        self.grade.addItem("")
        self.grade.addItem("")
        self.grade.addItem("")
        self.grade.addItem("")
        self.gridLayout_2.addWidget(self.grade, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Otchet"))
        self.createReportButton.setText(_translate("MainWindow", "Create Report"))
        self.percentageButton.setText(_translate("MainWindow", "Посчитать процент"))
        self.label.setText(_translate("MainWindow", " Часов в неделю:"))
        self.grade.setItemText(0, _translate("MainWindow", "J"))
        self.grade.setItemText(1, _translate("MainWindow", "M"))
        self.grade.setItemText(2, _translate("MainWindow", "S"))
        self.grade.setItemText(3, _translate("MainWindow", "L"))
        self.label_2.setText(_translate("MainWindow", "Грейд:"))
        self.label_3.setText(_translate("MainWindow", "%"))
