# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Py\Report_project\report_project_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMouseTracking(False)
        MainWindow.setAcceptDrops(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.repOutputLbl = QtWidgets.QLabel(self.centralwidget)
        self.repOutputLbl.setGeometry(QtCore.QRect(430, 10, 351, 521))
        self.repOutputLbl.setObjectName("repOutputLbl")
        self.createReportButton = QtWidgets.QPushButton(self.centralwidget)
        self.createReportButton.setGeometry(QtCore.QRect(10, 542, 781, 31))
        self.createReportButton.setObjectName("createReportButton")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(10, 10, 421, 521))
        self.textEdit.setObjectName("textEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Otchet"))
        self.repOutputLbl.setText(_translate("MainWindow", "    Report:"))
        self.createReportButton.setText(_translate("MainWindow", "Create Report"))
